
IF(NOT GLM_ROOT_DIR AND NOT $ENV{GLM_ROOT_DIR} STREQUAL "")
    SET(GLM_ROOT_DIR $ENV{GLM_ROOT_DIR})
ENDIF()

set(GLM_INCLUDE_DIR "${GLM_ROOT_DIR}\\include")

FIND_LIBRARY(GLM_LIBRARY
        NAMES
        libglm_shared
        HINTS
        ${GLM_ROOT_DIR}
        PATH_SUFFIXES
        lib64 lib
        )
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GLM DEFAULT_MSG
        GLM_LIBRARY GLM_INCLUDE_DIR)

IF(GLM_FOUND)
    SET(GLM_LIBRARIES ${GLM_LIBRARY})
    SET(GLM_INCLUDE_DIRS ${GLM_INCLUDE_DIR})
ENDIF()

MARK_AS_ADVANCED(
        GLM_INCLUDE_DIR
        GLM_LIBRARY
)